#!/usr/bin/env bash -e

# Note: use lowercase names for the Docker images
DOCKER_IMAGE="azureiotpcs/telemetry-agent-dotnet"

APP_HOME="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && cd .. && pwd )/"
source "$APP_HOME/scripts/.functions.sh"

run_container() {
    check_dependency_docker

    $APP_HOME/scripts/env-vars-check

    echo "Starting Telemetry Agent..."
    docker run -it -p 9023:9023 \
        -e PCS_TELEMETRYAGENT_DOCUMENTDB_CONNSTRING \
        -e PCS_TELEMETRY_WEBSERVICE_URL \
        -e PCS_CONFIG_WEBSERVICE_URL \
        -e PCS_IOTHUBMANAGER_WEBSERVICE_URL \
        -e PCS_IOTHUBREACT_AZUREBLOB_ACCOUNT \
        -e PCS_IOTHUBREACT_AZUREBLOB_KEY \
        -e PCS_IOTHUBREACT_AZUREBLOB_ENDPOINT_SUFFIX \
        -e PCS_IOTHUBREACT_HUB_NAME \
        -e PCS_IOTHUBREACT_HUB_ENDPOINT \
        -e PCS_IOTHUBREACT_ACCESS_CONNSTRING \
        "$DOCKER_IMAGE:testing"
}

run_container
